name: Build and test

on: [pull_request, push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19.0']
    steps:
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Install dependencies
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - run: go version
    - name: Build
      run: go build ./...
    - name: Test
      run: go test ./...
